# config/prod.exs
import Config

# Phoenix will read runtime settings from config/runtime.exs.
# Here we only put compile-time prod configuration.

# Serve digested static assets (generated by `mix assets.deploy`)
config :liveview, LiveviewWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Swoosh in prod uses Finch HTTP client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Liveview.Finch

# Do not print debug messages in production
config :logger, level: :info
